import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.swifttranslator.com/');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama pansal yanavaa');
  await expect(page.getByText('මම පන්සල් යනවා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('oya innavadha');
  await expect(page.getByText('ඔය ඉන්නවද')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.locator('body').press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('oya innavadhavamata haerenna');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('vamata haerenna');
  await expect(page.getByText('වමට හැරෙන්න')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('api nagareta enavaa');
  await expect(page.getByText('අපි නගරෙට එනවා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mata interview ekak thiyenavaa');
  await expect(page.getByText('මට interview එකක් තියෙනවා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama ehema karanne naehae');
  await expect(page.getByText('මම එහෙම කරන්නේ නැහැ')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama 25/02/2026 gedhara inne');
  await expect(page.getByText('මම 25/02/2026 ගෙදර ඉන්නේ')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('oyaage NIC number eka kiyanna mata');
  await expect(page.getByText('ඔයාගෙ NIC number එක කියන්න මට')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama gedhara yanavaa, passe api chithrapatayak balanavaa');
  await expect(page.getByText('මම ගෙදර යනවා, පස්සෙ අපි චිත්‍රපටයක් බලනවා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('karuNaakaralaa mata podi udhavvak karanna puLuvandha oyaata?');
  await expect(page.getByText('කරුණාකරලා මට පොඩි උදව්වක් කරන්න පුළුවන්ද ඔයාට?')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('iiLaGa sathiyee trip ekak plan karanavaa');
  await expect(page.getByText('ඊළඟ සතියේ trip එකක් plan කරනවා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('iiLaGa sathiyee trip ekak plan karanavaa');
  await expect(page.getByText('ඊළඟ සතියේ trip එකක් plan කරනවා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mata 2kg parippu ganna oonee');
  await expect(page.getByText('මට 2kg පරිප්පු ගන්න ඕනේ')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('eeyi, othanin palayan.');
  await expect(page.getByText('ඒයි, ඔතනින් පලයන්')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.locator('body').press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('eeyi, othanin palayan.api  vaeve  oru  padhinavaa');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('api  vaeve  oru  padhinavaa');
  await expect(page.getByText('අපි වැවෙ ඔරු පදිනවා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).dblclick();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('othanin ivath venna("avavaadhayayi!")');
  await expect(page.getByText('ඔතනින් ඉවත් වෙන්න("අවවාදයයි!")')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mata badaginii');
  await expect(page.getByText('මට බඩගිනී')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('het hamuvemu');
  await expect(page.getByText('හෙට් හමුවෙමු')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).dblclick();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('heta hamuvemu');
  await expect(page.getByText('හෙට හමුවෙමු')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('hari hari!, api 5.00pm vedhdhi othana.');
  await expect(page.getByText('හරි හරි!, අපි 5.00pm')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('havasata traffic thiyena nisaa kalin enna');
  await expect(page.getByText('හවසට traffic')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('magee NIC saha ID number dheka register karaganna oonee');
  await expect(page.getByText('මගේ NIC සහ ID number දෙක')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('api 2026-05-21 7.30 AM Colombo yanna hadhannee');
  await expect(page.getByText('අපි 2026-05-21 7.30 AM')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).dblclick();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Documents tika email karalaa manager ta evanna oonee ehema karoth work eka hariyata complete venavaa');
  await expect(page.getByText('Documents ටික email කරලා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('ela machan! api passe hamuvemu');
  await expect(page.getByText('එල මචන්! අපි පස්සෙ හමුවෙමු')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('adha udhaesana 6.30 AM mata aeharunaa. passe mama thee bona gaman phone eka check karalaa messages baluwa. 8.00 wenkota mama office yanna one, namuth traffic nisaa late venna puluvan. e nisaa mama driver ta call karAlaa kiyala, 9.00 AM enna kiyala schedule eka adjust karaa. lunch eken pASse maQQ documents tIka ready karalaa email ekak yavanna oone.');
  await expect(page.getByText('අද උදැසන 6.30 AM')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('adhanivaadudhavasak');
  await expect(page.locator('div').filter({ hasText: /^අදනිවාඩුදවසක්$/ })).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('adhanivaadudhavasakmm bth knw mm');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mm bth knw mm');
  await expect(page.getByText('mm බ්ත් ක්නw mm')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('today mama office go karala meeting attend kalaa');
  await expect(page.getByText('today මම office go කරල')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('ma ma ge dha ra ya na vaa');
  await expect(page.getByText('ම ම ගෙ ද ර ය න වා')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('hariii hariii lassanaiiii');
  await expect(page.getByText('හරීඉ හරීඉ ලස්සනෛඊඉ')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama gaava Rs@# 5000 thiyeyi!!!');
  await expect(page.getByText('මම ගාව Rs@# 5000 තියෙයි!!!')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('api\npaa\ndam\nkaranva');
  await expect(page.getByText('අපි පා dam කරන්ව')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('hetta vaeddee karramu');
  await expect(page.getByText('හෙට්ට වැඩ්ඩේ කර්‍රමු')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('aDha paaTha KaraNava');
  await expect(page.getByText('අධ පාථ ඛරණව')).toBeVisible();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('elaaa machannn');
  await expect(page.getByText('එලාඅ මචන්න්න්')).toBeVisible();
});